name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - sklearn
  - wget
  # - psutil
  # - toolz
  # - dill
  # - partd
  # - bokeh
  # - dask
